---
- name: Check kube-registry service status
  service_check:
    service_name: "kube_registry"
    service_type: "container"
  run_once: True
  when:
    - inventory_hostname in groups['registry']
  notify:
    - Restart kube-registry service