---
project_name: "ceph"

ceph_services:
  ceph-rgw:
    group: ceph-rgw
    enabled: "{{ enable_ceph_rgw|bool }}"
    haproxy:
      radosgw:
        enabled: "{{ enable_ceph|bool and enable_ceph_rgw|bool }}"
        mode: "http"
        external: false
        port: "{{ rgw_port }}"
      radosgw_external:
        enabled: "{{ enable_ceph|bool and enable_ceph_rgw|bool }}"
        mode: "http"
        external: true
        port: "{{ rgw_port }}"


####################
# Docker
####################
ceph_install_type: "source"
ceph_tag: "stein"

ceph_mds_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mds"
ceph_mds_tag: "{{ ceph_tag }}"
ceph_mds_image_full: "{{ ceph_mds_image }}:{{ ceph_mds_tag }}"

ceph_mon_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mon"
ceph_mon_tag: "{{ ceph_tag }}"
ceph_mon_image_full: "{{ ceph_mon_image }}:{{ ceph_mon_tag }}"

ceph_mgr_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mgr"
ceph_mgr_tag: "{{ ceph_tag }}"
ceph_mgr_image_full: "{{ ceph_mgr_image }}:{{ ceph_mgr_tag }}"

ceph_nfs_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-nfs"
ceph_nfs_tag: "{{ ceph_tag }}"
ceph_nfs_image_full: "{{ ceph_nfs_image }}:{{ ceph_nfs_tag }}"

ceph_osd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-osd"
ceph_osd_tag: "{{ ceph_tag }}"
ceph_osd_image_full: "{{ ceph_osd_image }}:{{ ceph_osd_tag }}"

ceph_rgw_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-rgw"
ceph_rgw_tag: "{{ ceph_tag }}"
ceph_rgw_image_full: "{{ ceph_rgw_image }}:{{ ceph_rgw_tag }}"

####################
# Ceph
####################
osd_initial_weight: "1"
ceph_debug: "no"

# Increase tcmalloc cache size
ceph_tcmalloc_tc_bytes: "134217728"

ceph_client_admin_keyring_caps:
  mds: "allow *"
  mon: "allow *"
  osd: "allow *"
  mgr: "allow *"

ceph_client_mgr_keyring_caps:
  mon: 'allow profile mgr'
  osd: 'allow *'
  mds: 'allow *'

ceph_client_mds_keyring_caps:
  mds: 'allow *'
  osd: 'allow *'
  mon: 'allow rwx'

partition_name_osd_bootstrap: "{{ 'KOLLA_CEPH_OSD_BOOTSTRAP_BS' if ceph_osd_store_type == 'bluestore' else 'KOLLA_CEPH_OSD_BOOTSTRAP' }}"
partition_name_cache_bootstrap: "{{ 'KOLLA_CEPH_OSD_CACHE_BOOTSTRAP_BS' if ceph_osd_store_type == 'bluestore' else 'KOLLA_CEPH_OSD_CACHE_BOOTSTRAP' }}"
partition_name_osd_data: "{{ 'KOLLA_CEPH_DATA_BS' if ceph_osd_store_type == 'bluestore' else 'KOLLA_CEPH_DATA' }}"

##########
# Ceph MDS
##########
cephfs_data_pool_name: "cephfs_data"
cephfs_data_pool_type: "{{ ceph_pool_type }}"
cephfs_data_pool_cache_mode: "{{ ceph_cache_mode }}"
cephfs_data_pool_pg_num: "{{ ceph_pool_pg_num }}"
cephfs_data_pool_pgp_num: "{{ ceph_pool_pgp_num }}"
cephfs_metadata_pool_name: "cephfs_metadata"
cephfs_metadata_pool_type: "{{ ceph_pool_type }}"
cephfs_metadata_pool_cache_mode: "{{ ceph_cache_mode }}"
cephfs_metadata_pool_pg_num: "{{ ceph_pool_pg_num }}"
cephfs_metadata_pool_pgp_num: "{{ ceph_pool_pgp_num }}"