---
- name: Ensure nfs volume exists
  file:
    name: "{{ nfs_volume }}"
    state: directory
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']

- name: Copy nfs exportfs for nfs-servers
  template:
    src: exports.j2
    dest: /etc/exports
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']
  notify:
    - Restart nfs-server service

- name: Check nfs-servers service status
  service_check:
    service_name: nfs-servers
    service_label: "{{ nfs_volume }}"
  when:
    - enable_nfs | bool
    - inventory_hostname in groups['storage']
  notify:
    - Restart nfs-server service