---
- name: Restart kube-loadbalancer container
  vars:
    service_name: loadbalancer
    service: "{{ loadbalancer_services[service_name] }}"
  become: true
  shell: docker run -d \
           --name {{ service.container_name }} \
           -v {{ loadbalancer_volumes }} \
           --net host \
           --restart=always {{ service.image }}
  when:
    - kolla_action != "config"