---
project_name: "kuryr-kubernetes"

kuryr_services:
  kuryr-kubernetes-controller:
    service_name: kuryr-kubernetes-controller
    group: kuryr-kubernetes-controller
    enabled: True
  kuryr-kubernetes-cni:
    service_name: kuryr-kubernetes-cni
    group: kuryr-kubernetes-cni
    enabled: True