---
project_name: "common"

# Due to the way we do our inventory, ansible does not pick up on the fact that
# this role has already run. We can track what has run with host facts.
common_run: False

common_services:
  kolla-toolbox:
    container_name: kolla_toolbox
    enabled: True
    image: "{{ kolla_toolbox_image_full }}"
    environment:
      ANSIBLE_NOCOLOR: "1"
      ANSIBLE_LIBRARY: "/usr/share/ansible"
    privileged: True
    volumes: "{{ kolla_toolbox_default_volumes + kolla_toolbox_extra_volumes }}"
    dimensions: "{{ kolla_toolbox_dimensions }}"
  # DUMMY_ENVIRONMENT is needed because empty environment is not supported

####################
# Docker
####################
common_install_type: "{{ kolla_install_type }}"
common_tag: "train"

kolla_toolbox_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ common_install_type }}-kolla-toolbox"
kolla_toolbox_tag: "{{ common_tag }}"
kolla_toolbox_image_full: "{{ kolla_toolbox_image }}:{{ kolla_toolbox_tag }}"

kolla_toolbox_dimensions: "{{ default_container_dimensions }}"

kolla_toolbox_default_volumes:
  - "{{ node_config_directory }}/kolla-toolbox/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "/dev/:/dev/"
  - "/run/:/run/:shared"
  - "kolla_logs:/var/log/kolla/"
kolla_toolbox_extra_volumes: "{{ default_extra_volumes }}"