---
network_interface: "eth0"
api_interface: "{{ network_interface }}"
api_interface_address: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"

aliyun_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers"

registry_address: "{{ hostvars[groups['registry'][0]]['ansible_' + api_interface]['ipv4']['address'] }}"
registry_port: 4000
registry_repo: "{{ registry_address }}:{{ registry_port }}"

#####################
# Kubernetes Options
#####################
kube_application_dir: "/tmp/kubernetes"

cluster_cidr: "172.30.0.0/16"
service_cidr: "10.254.0.0/16"

enable_registry: "yes"

enable_flanned: "yes"
enable_kubernetes: "yes"
enable_kubernetes_ha: "no"
enable_metrics_server: "yes"
enable_fluentd_elasticsearch: "yes"
enable_nfs_provisioner: "yes"
enable_dashboard: "yes"
enable_prometheus: "yes"
enable_jenkins: "no"

dashboard_node_port: 31000

kube_release: 1.16.2
kube_version: "v{{ kube_release }}"

docker_release: 18.06.2

node_config_directory: "/etc/kubernetes-ansible/"

metrics_server_images:
  - k8s.gcr.io/metrics-server-amd64:v0.3.6
  - k8s.gcr.io/addon-resizer:1.8.6

nfs_provisioner_images: quay.io/external_storage/nfs-client-provisioner:latest

kube_repo: "{{ registry_repo if enable_registry | bool else aliyun_repo }}"

kube_applications:
  - name: kube-flannel
    enabled: "{{ enable_flanned | bool }}"
  - name: dashboard
    enabled: "{{ enable_dashboard | bool }}"
  - name: metrics-server
    enabled: "{{ enable_metrics_server | bool }}"
  - name: nfs-provisioner
    enabled: "{{ enable_nfs_provisioner | bool }}"
  - name: grafana
    enabled: "{{ enable_grafana | bool }}"
  - name: prometheus
    enabled: "{{ enable_prometheus | bool }}"
  - name: jenkins
    enabled: "{{ enable_jenkins | bool }}"


###############
# Nfs Options
###############
enable_nfs: "yes"

nfs_volume: /data/share
nfs_cidr: 172.16.50.0/24


##################
# Grafana Options
##################
enable_grafana: "no"
