---
- name: Reset the kubernetes cluster
  kube_toolbox:
    module_name: kubeadm
    module_args: "reset -f"
  when: inventory_hostname in groups['kubernetes']

- name: Destroy loadbalancer role
  import_role:
    role: loadbalancer
  when: enable_kubernetes_ha | bool

- name: Ensure kubernetes worker dir not exists
  file:
    name: "{{ kube_application_dir }}"
    state: absent
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
