---
- name: Drain the kube worker from kubernetes cluster
  sdnhub_kube:
    module_name: kubectl
    module_args: "drain {{ item }} --delete-local-data --force --ignore-daemonsets"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
  loop: "{{ groups['kube-worker'] }}"

- name: Remove the kube worker from kubernetes cluster
  sdnhub_kube:
    module_name: kubectl
    module_args: "delete node {{ item }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: True
  loop: "{{ groups['kube-worker'] }}"

- name: Reset the kubernetes cluster
  sdnhub_kube:
    module_name: kubeadm
    module_args: "reset -f"
  when: inventory_hostname in groups['kubernetes']