---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/loadbalancer"
    state: "directory"
  become: true
  with_dict: "{{ loadbalancer_services }}"
  when: inventory_hostname in groups['kubernetes']

- name: Copy loadbalancer confs
  template:
    src: lb-nginx.conf.j2
    dest: "{{ node_config_directory }}/loadbalancer/lb-nginx.conf"
  become: true
  when: inventory_hostname in groups['kubernetes']
  notify:
    - "Restart kube-loadbalancer container"

- name: Check loadbalancer containers
  become: true
  kolla_docker:
    action: "compare_container"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ loadbalancer_services }}"
  notify:
    - "Restart kube-loadbalancer container"