---
- import_playbook: gather-facts.yml

- name: Apply role ceph
  gather_facts: false
  hosts:
    - ceph-mds
    - ceph-mgr
    - ceph-mon
    - ceph-nfs
    - ceph-osd
    - ceph-rgw
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - { role: ceph,
        tags: ceph,
        when: enable_ceph | bool }

- name: Apply role kubernetes
  gather_facts: false
  hosts:
    - kube-master
    - kube-worker
    - kubernetes
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - { role: kubernetes,
        tags: kubernetes,
        when: enable_kubernetes | bool }
